### ISSUE TITLE
'G.add_edge_e g edge' is slow

### ISSUE THREAD

**Issue by UnixJunkie** [backtracking/ocamlgraph#105]
Hello,

I have a dense graph with about 1000 nodes.
Adding all the edges to the graph is quite slow.
Since I have an almost all to all connectivity, is there
a way to make it faster?
Like, reserving the number of successors to a node at graph construction time?

For example, at graph creation time we say:
 ```
module G = Graph.Imperative.Graph.ConcreteLabeled(Node)(Edge)

G.create ~size:nb_nodes (* reserve enough nodes *)
```

Thanks,
F.

**Comment by signoles** [comment]
The efficiency also depends of the function you provide within modules `Node` and `Edge`: Using `Imperative.Graph.AbstractLabeled` might be more efficient (see http://ocamlgraph.lri.fr/doc/Imperative.S.html for a brief discussion about this choice).

I think that reserving the nodes in advance would not speed up the implementation significantly. Yet it is easy to have a try by applying the following patch (you may replace 2099 by any number of your convenience):
```
diff --git a/src/blocks.ml b/src/blocks.ml
index 3e7a99d..c865ff2 100644
--- a/src/blocks.ml
+++ b/src/blocks.ml
@@ -77,7 +77,7 @@ module Make_Hashtbl(X: COMPARABLE) = struct
      constraints *)
 
   let create_from h = create (length h)
-  let create ?(size=97) () = create size
+  let create ?(size=2099) () = create size
 
   let is_empty h = (length h = 0)
```

Last but not least, the implementation of graph datastructures in OCamlGraph are quite generic and not optimized for a particular kind of graphs (e.g., dense graphs). Yet, it is possible to write your own optimized datastructure for dense graphs, and still use the graph algorithms (Dijkstra, etc) provided by our library. That is one of the strengths of being heavily based on functors.

**Comment by UnixJunkie** [comment]
I was reserving the exact number of nodes required already.

**Comment by UnixJunkie** [comment]
I am using this currently, note that I am almost a complete beginner with ocamlgraph:
```
module Node = struct
  type t = int
  let compare = BatInt.compare
  let hash = Ht.hash
  let equal = BatInt.equal
  let default = 0
end

module Edge = struct
  type t = float
  let compare = BatFloat.compare
  let hash = Ht.hash
  let equal = BatFloat.equal
  let default = 0.0
end

module G = Graph.Imperative.Graph.ConcreteLabeled(Node)(Edge)

module W = struct
  type label = G.E.label
  type edge = G.E.t
  type t = float (* mandatory *)
  let weight x = G.E.label x
  let zero = 0.0
  let add = (+.)
  let compare = BatFloat.compare (* mandatory *)
end

module Kruskal = Graph.Kruskal.Make(G)(W)
```

**Comment by UnixJunkie** [comment]
So, my nodes have an integer identifier.
For the edges, I just care that they carry a (positive) float weight (no label is OK).
Then, I want to compute the minimum spanning tree over this graph.
I was planning to use ocamlgraph just as a "service" library.
I don't think I will hack my own graph implementation.
Note that the biggest graph I will attack should have around 300,000 nodes.
The smallest will have maybe tens on nodes.

**Comment by signoles** [comment]
A dense graph of 300,000 nodes has about 90,000,000,000 edges. The complexity of the Kruskal algorithm is O(E log (E)) with E = the number of edges. It may explain why it is slow... As far as I know, OCamlGraph scales quite well up to millions of edges. I don't know for several billions... `Imperative.Matrix` datastructures could scale better but you cannot have label on edges in such graphs.

I think that, for such a size, you must rely on an optimized implementation. I am not an expert in graph algorithms. Yet, a quick search points me out the [Prim's algorithm](https://en.wikipedia.org/wiki/Prim%27s_algorithm) as a replacement of the Kruskal's algorithm for dense graphs (linear complexity in that case).

**Comment by backtracking** [comment]
The module Imperative.Graph.ConcreteLabeled you are using is
implementing graphs using hash tables: a hash table is mapping each
vertex to the set of its successors, this set being also implemented
with a hash table. This way, operations such as adding/querying/removing
nodes and edges are all constant time.

This comes at a space cost, though, even if this stays proportional to
the size of the graph.

For a dense graph with 1000 nodes, that is with roughly one million
edges, building all these hash tables indeed takes some time. I just
made a quick experiment on my machine: it takes 13 seconds and it is
using ~ 93 Mb of memory.

If instead we switch to Imperative.Matrix, that implements graphs using
an adjacency matrix, then it is built in no time (0.01 seconds) and it
is only using 3.75 Mb. And you can provide your weight function on the
side, as a function of type int->int->float, instead of having edges
labeled with floats.

Now, you are also mentioning graphs with 300,000 nodes. If these are
dense, it is unlikely you'll have enough space to build them in memory.

--
Jean-Christophe

**Comment by UnixJunkie** [comment]
Thanks for the hints.
In the recent past, I could compute the N*N matrix for 300,000 elements using a machine with 128GB of RAM.

**Comment by UnixJunkie** [comment]
I'll tell how it goes once I manage to use Imperative.Matrix.

**Comment by UnixJunkie** [comment]
I am closing this, because not a bug, rather a performance question.
Thanks for the hints.
