### ISSUE TITLE
Question : initial size of hash table

### ISSUE THREAD

**Issue by ddemange** [backtracking/ocamlgraph#135]
A hashtable is used to compute a weak topological ordering of the nodes of the graph.

https://github.com/backtracking/ocamlgraph/blob/4ad137fcd5ad0e04746179165fb31685a2e14790/src/weakTopological.ml#L52

Just out of curiosity, is there any particular reason for choosing 1024 as the (initial) size of the hashtable ?
I find it surprising that it is not related in any way to the size of the graph.
I might be missing something.

**Comment by zapashcanon** [comment]
This is because of the stdlib. [Here](https://github.com/ocaml/ocaml/blob/trunk/stdlib/hashtbl.ml#L74) you can see that `create` is going to use the power of two just above the size you give it. If it's already a power of two then it'll be faster.

IIRC the change was made around 2006. Before it was better to use a prime number for some reason that I forgot.

>  I find it surprising that it is not related in any way to the size of the graph.

Regarding why using `1024` and not `512` or something related to the size of the graph ; my guess is that it would be possible and probably more efficient in some cases. On the other hand I guess this does not matter too much in practice so people tend to simply use a power of two.

I'm not the author of the library, @backtracking could probably tell you more.

**Comment by backtracking** [comment]
@ddemange You're right, even though OCaml's hash tables are internally resizing as needed, it is slightly more efficient to start with a capacity that is the expected order of magnitude. So here we could indeed use `nb_vertex g` rather than 1024.

That being said, @zapashcanon is right about the fact that, if we choose a capacity arbitrarily, we can stick to a power of two, as the implementation will take a power of two anyway.

**Comment by ddemange** [comment]
Thank you @backtracking and @zapashcanon. This clarifies the situation. I guess only a proper benchmarking process, on a precise use case, can provide more fine-grained arguments as to how the initial size should (or can) be picked.
