### ISSUE TITLE
1.8.6 changes to Dominator.Make causes breakage

### ISSUE THREAD

**Issue by jonludlam** [backtracking/ocamlgraph#33]
I'm not sure whether this is intentional or not, but the Make functor from src/dominator.ml no longer creates a module that exposes the 'compute_all' function. 

If it's intentional, it should probably have an asterisk in the CHANGES file. If not, could it be fixed? This causes dose3 to fail to build (due to [this](https://gforge.inria.fr/plugins/scmgit/cgi-bin/gitweb.cgi?p=dose/dose.git;a=blob;f=algo/dominators.ml;h=d24ae0944718eccd6ebc586ac2f2cf49b3fa6dca;hb=8410320f859d8833f2580c65fc76959cb7c3531a#l103))

**Comment by signoles** [comment]
Thanks for the report.

This is intentional to be able to apply the functor [Make] with a read-only graph. If you need the function [compute_all] (or [compute_dom_graph]), you now have to use the new functor [Make_graph]. which requires functions to generate new graphs ([create] and [add_edge]).

I have just updated the file CHANGES to document this incompatible changes as you expect.
