### ISSUE TITLE
Proposition for important entry in FAQ

### ISSUE THREAD

**Issue by wieczyk** [backtracking/ocamlgraph#73]
Hey,

I think it is interesting to explicitly write information (for example in FAQ) if it is possible to update imperative graph during traversal done by `fold_vertex` or `iter_vertex`.

**Comment by backtracking** [comment]
Good point.

Imperative graphs being implemented with hash tables, the answer is no.

Workarounds include
- storing update information on the side, then apply it in a second step;
- mutate a second graph instead.

Regarding the latter, it is worth pointing out OCamlgraph also provides
immutable graphs that could make it more efficient (free ``copy'' and
possible sharing between the two graphs, at the extra cost of
logarithmic operations instead of constant-time operations).

I've updated the FAQ accordingly.

--
Jean-Christophe
