### ISSUE TITLE
DFS and BFS use a strange order

### ISSUE THREAD

**Issue by eponier** [backtracking/ocamlgraph#86]
During some tests with the `Traverse` module, @ThomasRuby and I were surprised by the orders chosen by `DFS` and `BFS`. Initially, I wrongly believed that both were somehow looking for nodes with no predecessors, but instead, they use the arbitrary order returned by `fold_vertex` or `iter_vertex`. More precisely, they perform a DFS or a BFS for each node returned by one of these functions if it has not been seen yet (and each traversal also ignores nodes seen by each previous traversal).

For instance, let us consider the following diamond graph:
`g : u1 -> u2, u1 -> u3, u2 -> u4, u3 -> u4`
If `iter_vertex` traverses nodes in the order `[1; 2; 3; 4]` (or any other order that begins with `1`), the `DFS` or the `BFS` starts a traversal at node `1`, visits all the nodes, and then do nothing for the subsequent calls on nodes `2`, `3` and `4`. From the point of view of the user, this amounts to a single traversal from node `1`, and this is what is expected.

On the contrary, if `iter_vertex` traverses nodes in the order `[4; 2; 3; 1]`, then the `DFS` or the `BFS` starts a traversal at node `4` that stops immediately since `4` has no children, then perform a traversal at node `2` that stops immediately since the only child, `4`, has already been processed, and similarly for `3` and `1`. This means that, whether we perform a DFS prefix, a DFS postfix or a BFS, nodes are systematically processed in the same order, i.e. `[4; 2; 3; 1]`. For me, in this case, it actually does not look like a DFS or BFS traversal.

I consider there are four solutions:
- consider this is the normal behaviour (though, in my opinion, it makes some sense only in the case of a postfix DFS since, at least, the property that each node is visited after its children is observed), and better document it;
- change the comment 
  > It is enough to iter over all the roots (vertices without predecessor) of the graph, even if iterating over the other vertices is correct.

  in the [documentation](http://ocamlgraph.lri.fr/doc/Traverse.G.html) into
  > Be careful to iter only over all the roots (vertices without predecessor) of the graph

  (but certainly in this case, the functions should not be named `fold_vertex` and `iter_vertex` anymore);

- add to the functions some additional argument specifying the initial node(s);
- as suggested in the first paragraph, look for nodes with no predecessors before performing any traversal.

**Comment by backtracking** [comment]
Indeed, it may seem confusing at first sight. But there is nothing wrong with this API (unless I'm mistaken).

The idea is that the meaningful functions are rather iter/fold_component, where the starting point of the DFS is user-provided. I guess this is exactly what you suggest in your third solution.
If you look for instance in Sedgewick&Wayne's Algorithms, you'll see that this is the only function in the DFS API. See https://algs4.cs.princeton.edu/41graph/DepthFirstSearch.java.html

The iter and fold functions are also provided, for your convenience. Indeed they perform as you observed: they run the user-provided iter/fold_vertex functions and, for each vertex not yet visited, start a new DFS from this vertex. Hence the rather cryptic comment saying that iterating over DFS roots only is fine. Said otherwise, it is up to you to come up with an iter_vertex function that will identify suitable DFS roots,  e.g. vertices with no predecessors.

My understanding is that you'd like some additional function in the DFS API that would identify vertices with no predecessors for you and run DFS from these vertices. Indeed we could do that, though it would raise some issues such as what to do when you have a strongly-connected component (i.e. with no vertex with no predecessors).

I hope I understood your question correctly.

**Comment by eponier** [comment]
You perfectly understood my question and carefully answered it.

I had missed the documentation of `fold` in `DFS` that could have hinted me in the right direction.

> The function is applied each time a node is reached for the first time, before idoterating<sup>1</sup> over its successors. Tail-recursive.

I think the main issue, here, is documentation. A few points could be improved:
- The functions in `BFS` could get the same documentation as in `DFS`. For instance, the documentation quoted above appears only in `DFS`.
- The documentation could highlight that the `*_component` versions are probably the ones to be used.
- The descriptions of `iter_vertex` and `fold_vertex` could explain that the order is important if the user wants to use the non-component versions of the functions.

Thanks for taking the time to answer me!

<sup>1</sup>The typo is present in the documentation.

**Comment by backtracking** [comment]
Fixed in commit a2d7918.
